### ISSUE TITLE
MotifSeq produces a syntax error

### ISSUE THREAD

**Issue by shaniAmare** [Psy-Fer/SquiggleKit#11]
Hi again James....

Thank you for your response throughout! 

I am running MotifSeq.oy now - And came across this error:
`Traceback (most recent call last):`
 `File "SourceFiles/SquiggleKit-master/MotifSeq.py", line 10, in <module>
    from mlpy import dtw_subsequence`
  `File "SourceFiles/mlpy-3.5.0/mlpy/__init__.py", line 18, in <module>`
    `import gsl`
 `File "SourceFiles/gsl/__init__.py", line 8`
    `raise ValueError(f"name must be a legal identifier: {name}")`
 `        `                                                     ^
`SyntaxError: invalid syntax`

The script for 'MotifSeq.py':
`# creating the model`
`scrappie squiggle ${out_dir}/squigglemotifseq/barcodes.fa > ${out_dir}/squigglemotifseq/adapter.model`
`# running MotifSeq.py`
`for file in ${out_dir}/squigglepull/*.gzip` 
`do` 
`prefix=${file##*/}; prefix=${prefix%%.*};` 
`stall=${out_dir}/squigglesegmenter/${prefix}_signals_stall_segments.tsv`
`python ${sourceFiles}/SquiggleKit-master/MotifSeq.py -s ${file} --segs ${stall} -a ${out_dir}/squigglemotifseq/adapter.model > \` `${out_dir}/squigglemotifseq/${prefix}_signals_adapters.tsv`
`done`

Would really appriciate your feedback!

Cheers,
Shani.

**Comment by Psy-Fer** [comment]
Hello again.

I have made a boo boo. I assumed IF people were going to gzip files, they would have the `.gz` extension. So this could also be a source of the problem.

A quick solution to this would be to rename the file with a `.gz` instead of `.gzip` extension

Noted it and this will be fixed in upcoming update. Thanks for finding it!

If that doesn't work, could you kindly do the following to your files and send them to me?

`head adapter.model`
`head *_signals_adapters.tsv` (just one of them is fine, assuming there are a few)
`head *_signals_stall_segments.tsv` (same for this, one is fine)

cheers,
James

**Comment by shaniAmare** [comment]
Hi James,

Happy if it was any help.

Anyway, these are the info you asked for
` head adapter.model`
`#Lib10_000000`
`pos     base    current sd      dwell`
`0       T       0.424061        0.392558        0.413294`
`1       A       -0.207713       0.299440        0.701073`
`2       G       -1.490382       0.243177        3.213416`
`3       A       -0.618917       0.164932        6.746379`
`4       C       1.083751        0.133738        7.949336`
`5       C       0.148915        0.126884        7.131965`
`6       A       -0.770644       0.161298        6.865753`
`7       T       1.810512        0.209488        7.282195`

`head *_signals_squigglepull.tsv # output from squigglepull`
[example_data_squigglepull.csv.gz](https://github.com/Psy-Fer/SquiggleKit/files/3130078/example_data_squigglepull.csv.gz)
`head *_signals_stall_segments.tsv # output from segmenter`
[example_signals_stall_squigglesegment.csv.gz](https://github.com/Psy-Fer/SquiggleKit/files/3130077/example_signals_stall_squigglesegment.csv.gz)
`head *_signals_adapters.tsv #output from motifseq`
[example_signals_adapters.tsv.gz](https://github.com/Psy-Fer/SquiggleKit/files/3130108/example_signals_adapters.tsv.gz)

You are right... The reason for `MotifSeq.py` to fail on me is because it was looking for an `.gz` extension (stupid me!). I tried temporarily changing all occurrences in your script that asked for a `.gz` file to `.gzip`, and it worked.

 It would be really appreciated if you can let me know whether the outputs attached here are similar to what you'd expect.

Thanks a lot,
Shani.

**Comment by shaniAmare** [comment]
Also James, it would be really great if you could kindly add explanations of the outputs of each step to your wiki.

Cheers,
Shani.

**Comment by Psy-Fer** [comment]
Hey Shani,

Glad that worked for you. 

Everything looks fine otherwise.

SquiggleKit is currently going through review and so there is a bit going on in the background which will make these tools a bit more transparent in what is going on. Documentation to follow after the big update coming.

The core principles will be the same, it's just adding extra functionality, or cleaning up how everything works, adding sanity checks, and helps the user by doing more automatically.

I hope the delay in the update isn't too much of an inconvenience.

Regards,
James
