### ISSUE TITLE
dRNA SquiggleKit

### ISSUE THREAD

**Issue by pabloacera** [Psy-Fer/SquiggleKit#23]
Hi James!

Thanks for the awesome tool! I am interesting in looking at RNA signals and I was wondering If SquiggleKit is already able to manipulate dRNA. If that is the case, how well tools like MotifSeq works?? 
I have realize that when doing the re-squiggle of dRNA signals with Tombo, these have higher noise than the DNA squiggle ones. I guess that both the pores and the software are not as polished with dRNA? Do you have any thoughts on this?

Thank you very much for your time in advance!
Very much appreciated, 
Cheers,
Pablo.

**Comment by Psy-Fer** [comment]
Hello Pablo

Motifseq can indeed work with dRNA, as it uses the scrappie RNA model to approximate a synthetic signal. 

The background modelling however won't be accurate, as I have not benchmarked it on dRNA. 

Segmenter may give some odd results too because of the adapter sequence at the beginning.

I have a tool being released soon which can segment that region specifically. 

Some thoughts on the accuracy. I think when you have more samples per nucleotide, you have more potential for ionic noise as well, which plays havoc with many classical algorithmic methods, such as tombo and SquiggleKit. I would expect a small improvement with the release of the RNA003 kit, which will speed up the translation, and drop some of the noise.

**Comment by pabloacera** [comment]
Hi James,

Thanks for the comments. Looking forward to use that new tool, we were also looking for tools to trim the adapter in dRNA signals. Also finger cross with the RNA003 kit.
Thanks again,
Cheers,
Pablo.

**Comment by Psy-Fer** [comment]
Hello.
If you check my other pinned repo, you will find what I was referring to.
I'll close this case. Good luck :)
