### ISSUE TITLE
SquigglePull.py cannot be executed properly

### ISSUE THREAD

**Issue by shaniAmare** [Psy-Fer/SquiggleKit#9]
Hi James,

I am trying to use `SqugglePull.py` in hope of retrieving some  extra information from the `fast5` files. I attempted following two scripts:
` python3 $sourceFiles/SquiggleKit-master/SquigglePull.py -r -p $fast5_dir1 -f all > $out_dir1/2-A1-D1-data.tsv ` 
which results in no output
`python3 $sourceFiles/SquiggleKit-master/SquigglePull.py -rv -p $fast5_dir1 -f all > $out_dir1/2-A1-D1-data.tsv`
which results in following error:
`Traceback (most recent call last):
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/GridION_pilot_Dec18/SourceFiles/SquiggleKit-master/SquigglePull.py", line 357, in <module>
    main()
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/GridION_pilot_Dec18/SourceFiles/SquiggleKit-master/SquigglePull.py", line 112, in main
    print >> sys.stderr, "Verbose mode on. Starting timer"
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
`

Am I doing something naive over here? I'm using the latest clone from the SquiggleKit GitHub repo. My `fast5` files are in `.tar.gz` format. They are in `multi fast5` format.  But I don't think that it matters now? I'm happy to give more information if what I've provided here are insufficient.

Thanks a lot for your help and look forward to using this useful tool soon!

Cheers,
Shani.

**Comment by Psy-Fer** [comment]
Hello Shani,

Currently multi fast5 files are not supported. Please see this https://github.com/Psy-Fer/SquiggleKit/issues/5#issuecomment-474153294 to see the solution to this.

It is to use the nanopore multi to single fast5 conversion tool.
I have implemented a multifast5 reader, however it is still undergoing testing. I don't have a timeline yet for the release. Next few weeks at the latest though.

Also, the error is because you are using python 3. SquiggleKit currently works with python 2.7+ with python 3 compatibility in the works (as someone was already kind enough to make a pull request for it).

Let me know if I can help in any other way.

James.

**Comment by shaniAmare** [comment]
Thanks James.
I used the solution you gave me (i.e. using single line `fast5` files as the input) and in `Python2` env. it gives me an output. I will update once it is completed. But I think it is safe to close this issue for now.
Cheers,
Shani.

**Comment by Psy-Fer** [comment]
No worries. Give me a shout if you need anything else.

**Comment by Psy-Fer** [comment]
Hey Shani,

SquigglePull now supports multifast5 file input, using the `--multi` argument.
It's a quick hack for now till I overhaul it more.

James

**Comment by shaniAmare** [comment]
Cool Thanks James. :)

Cheers,
Shani.
________________________________
